{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8a820786",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'flask'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn [1], line 31\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[38;5;124;03mPRODUCTION SETUP:\u001b[39;00m\n\u001b[1;32m      6\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     27\u001b[0m \u001b[38;5;124;03mFrontend → API (Cloud Run) → Returns image URLs → CDN → GCS bucket\u001b[39;00m\n\u001b[1;32m     28\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m     30\u001b[0m \u001b[38;5;66;03m# Updated Flask app for production\u001b[39;00m\n\u001b[0;32m---> 31\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mflask\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Flask, request, jsonify\n\u001b[1;32m     32\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01minference\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ModelServer\n\u001b[1;32m     33\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mos\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'flask'"
     ]
    }
   ],
   "source": [
    "# Recommended Architecture for homepay.sg\n",
    "# ====================================\n",
    "\n",
    "\"\"\"\n",
    "PRODUCTION SETUP:\n",
    "\n",
    "1. Images: Google Cloud Storage bucket\n",
    "   - Bucket: gs://homepay-prod-images/\n",
    "   - Public read access\n",
    "   - Lifecycle rules for cost optimization\n",
    "\n",
    "2. Model: Google Cloud Run (or Kubernetes)\n",
    "   - Container with model files only (no images)\n",
    "   - Auto-scaling based on traffic\n",
    "   - Multiple regions for low latency\n",
    "\n",
    "3. CDN: Cloud CDN or Cloudflare\n",
    "   - Cache images globally\n",
    "   - Reduce costs and improve speed\n",
    "\n",
    "4. API: RESTful endpoints\n",
    "   - /search - semantic search\n",
    "   - /similar - find similar images  \n",
    "   - /recommendations - user-based recs\n",
    "\n",
    "Architecture Flow:\n",
    "Frontend → API (Cloud Run) → Returns image URLs → CDN → GCS bucket\n",
    "\"\"\"\n",
    "\n",
    "# Updated Flask app for production\n",
    "from flask import Flask, request, jsonify\n",
    "from inference import ModelServer\n",
    "import os\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Configuration\n",
    "BUCKET_NAME = os.environ.get('BUCKET_NAME', 'homepay-prod-images')\n",
    "CDN_BASE_URL = os.environ.get('CDN_BASE_URL', f'https://storage.googleapis.com/{BUCKET_NAME}/')\n",
    "\n",
    "# Initialize model (no images needed in container)\n",
    "model_server = ModelServer()\n",
    "\n",
    "@app.route('/search', methods=['POST'])\n",
    "def search():\n",
    "    data = request.get_json()\n",
    "    query = data.get('query', '')\n",
    "    top_k = data.get('top_k', 20)\n",
    "    \n",
    "    try:\n",
    "        # Get recommendations (returns image_ids and scores)\n",
    "        results = model_server.search(query, top_k)\n",
    "        \n",
    "        # Convert to full response with URLs\n",
    "        response = {\n",
    "            'success': True,\n",
    "            'query': query,\n",
    "            'results': [\n",
    "                {\n",
    "                    'image_id': image_id,\n",
    "                    'image_url': f\"{CDN_BASE_URL}{image_id}\",\n",
    "                    'score': float(score),\n",
    "                    'metadata': model_server.rec_system.data.get(image_id, {})\n",
    "                }\n",
    "                for image_id, score in results\n",
    "            ]\n",
    "        }\n",
    "        \n",
    "        return jsonify(response)\n",
    "        \n",
    "    except Exception as e:\n",
    "        return jsonify({'success': False, 'error': str(e)}), 500\n",
    "\n",
    "@app.route('/similar/<image_id>', methods=['GET'])\n",
    "def get_similar(image_id):\n",
    "    top_k = request.args.get('top_k', 20, type=int)\n",
    "    user_id = request.args.get('user_id')\n",
    "    \n",
    "    try:\n",
    "        results = model_server.get_similar(image_id, user_id=user_id, top_k=top_k)\n",
    "        \n",
    "        response = {\n",
    "            'success': True,\n",
    "            'reference_image': {\n",
    "                'image_id': image_id,\n",
    "                'image_url': f\"{CDN_BASE_URL}{image_id}\"\n",
    "            },\n",
    "            'similar_images': [\n",
    "                {\n",
    "                    'image_id': similar_id,\n",
    "                    'image_url': f\"{CDN_BASE_URL}{similar_id}\",\n",
    "                    'score': float(score)\n",
    "                }\n",
    "                for similar_id, score in results\n",
    "            ]\n",
    "        }\n",
    "        \n",
    "        return jsonify(response)\n",
    "        \n",
    "    except Exception as e:\n",
    "        return jsonify({'success': False, 'error': str(e)}), 500\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
